name: Code Coverage

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10.4"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Test with pytest
        run: |
          PERC_COV="$(python -m pytest --cov=src --cov-report term | grep TOTAL | grep -oP "[0-9]+%")"
          NUM_COV="$(echo $PERC_COV | grep -oP [0-9]+)"
          echo "COVERAGE=$(echo $PERC_COV)" >> $GITHUB_ENV
          echo "COVERAGE_NUM=$(($NUM_COV))" >> $GITHUB_ENV
      - name: Create Coverage Badge
        uses: schneegans/dynamic-badges-action@v1.6.0
        with:
          auth: ${{ secrets.GIST_SECRET }}
          gistID: 4c379c3359827d18faef6e848a501031
          filename: regex-query-tool-coverage.json
          label: coverage
          message: ${{ env.COVERAGE }}
          valColorRange: ${{ env.COVERAGE_NUM }}
          maxColorRange: 70
          minColorRange: 30

