name: Code Coverage Summary

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10.4"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      #- name: Test with pytest
      #  run: |
      #    python -m pytest --cov=src --cov-report xml:coverage/coverage.xml
      - name: Build coverage file
        run: |
          mkdir -p coverage
          coverage run -m pytest --cache-clear --junitxml=coverage/pytest.xml --cov=src/ --cov-report=term-missing | tee coverage/pytest-coverage.txt
      - name: Pytest coverage comment
        uses: MishaKav/pytest-coverage-comment@main
        with:
          pytest-coverage-path: ./coverage/pytest-coverage.txt
          junitxml-path: ./coverage/pytest.xml
          badge-title: coverage